### ISSUE TITLE
no such command `shell'

### ISSUE THREAD

**Issue by lethjakman** [OiNutter/nodenv#9] opened 2014-11-04 16:51 UTC
When I run nodenv shell I get this error:

``` bash
$ nodenv shell
nodenv: no such command `shell'
```

It appears that the command 'shell' is under the wrong path. I found it [here](https://github.com/OiNutter/nodenv/blob/master/libexec/nodenv-sh-shell), and it appears that since the file is named nodenv-sh-shell rather than nodenv-shell that the nodenv executable can't find it and when I rename it it works properly. Could this file perhaps be named wrong? 

Thank you for your time!

**Comment by toolbear** [comment] 2015-02-23 16:27
Same problem here. My workaround is to run it like `nodenv sh-shell v0.10.31`

**Comment by jasonkarns** [comment] 2015-10-16 20:54
could you provide a gist of your output with NODENV_DEBUG enabled? `NODENV_DEBUG=1 nodenv shell`

Also, be sure you're on the latest version 7594630563bc65591c185a48d29d85268f174959

There were some potentially-related changes from rbenv upstream that may impact this. (Coincidentally, if you also happen to be an rbenv user, could you see if `rbenv shell` works or not?)

**Comment by jasonkarns** [comment] 2015-11-10 22:10
closing due to time. assuming latest changes from rbenv have resolved this. If either @toolbear or @lethjakman are still able to reproduce after upgrading nodenv, we can reopen

**Closed by jasonkarns** 2015-11-10 22:10 UTC

**Comment by Tehnix** [comment] 2018-02-20 08:26
I just ran into this (the `nodenv: no such command 'shell'`) running `nodenv 1.1.2`.

Running with `NODENV_DEBUG=1` gave me,

```
+ [nodenv:23] enable -f /usr/local/Cellar/nodenv/1.1.2/libexec/nodenv-realpath.dylib realpath
+ [nodenv:53] '[' -z '' ']'
+ [nodenv:54] NODENV_ROOT=/Users/christiankjaerlaustsen/.nodenv
+ [nodenv:58] export NODENV_ROOT
+ [nodenv:60] '[' -z '' ']'
+ [nodenv:61] NODENV_DIR=/Users/christiankjaerlaustsen/Bitbucket/Grundfos/manual-input
+ [nodenv:67] export NODENV_DIR
+ [nodenv:70] shopt -s nullglob
++ [nodenv:72] abs_dirname /usr/local/bin/nodenv
+++ [nodenv:25] realpath /usr/local/bin/nodenv
++ [nodenv:25] local path=/usr/local/Cellar/nodenv/1.1.2/libexec/nodenv
++ [nodenv:26] echo /usr/local/Cellar/nodenv/1.1.2/libexec
+ [nodenv:72] bin_path=/usr/local/Cellar/nodenv/1.1.2/libexec
+ [nodenv:76] export PATH=/usr/local/Cellar/nodenv/1.1.2/libexec:/usr/local/opt/texinfo/bin:/Users/christiankjaerlaustsen/.rbenv/shims:/usr/local/opt/rbenv/bin:/usr/local/opt/pyenv/shims:/usr/local/opt/pyenv/bin:/Users/christiankjaerlaustsen/.nix-profile/bin:/Users/christiankjaerlaustsen/.nix-profile/sbin:/Users/christiankjaerlaustsen/.nix-profile/lib/kde4/libexec:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/nix/var/nix/profiles/default/lib/kde4/libexec:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/opt/texinfo/bin:/Users/christiankjaerlaustsen/.rbenv/shims:/usr/local/opt/rbenv/bin:/usr/local/opt/pyenv/shims:/usr/local/opt/pyenv/bin:/Users/christiankjaerlaustsen/.nix-profile/bin:/Users/christiankjaerlaustsen/.nix-profile/sbin:/Users/christiankjaerlaustsen/.nix-profile/lib/kde4/libexec:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/nix/var/nix/profiles/default/lib/kde4/libexec:/Users/christiankjaerlaustsen/Bitbucket/blackbird/cli/bin:/Users/christiankjaerlaustsen/.local/go/bin:/Users/christiankjaerlaustsen/.local/bin:/usr/local/sbin:/Users/christiankjaerlaustsen/.cargo/bin:/Users/christiankjaerlaustsen/.rvm/bin
+ [nodenv:76] PATH=/usr/local/Cellar/nodenv/1.1.2/libexec:/usr/local/opt/texinfo/bin:/Users/christiankjaerlaustsen/.rbenv/shims:/usr/local/opt/rbenv/bin:/usr/local/opt/pyenv/shims:/usr/local/opt/pyenv/bin:/Users/christiankjaerlaustsen/.nix-profile/bin:/Users/christiankjaerlaustsen/.nix-profile/sbin:/Users/christiankjaerlaustsen/.nix-profile/lib/kde4/libexec:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/nix/var/nix/profiles/default/lib/kde4/libexec:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/opt/texinfo/bin:/Users/christiankjaerlaustsen/.rbenv/shims:/usr/local/opt/rbenv/bin:/usr/local/opt/pyenv/shims:/usr/local/opt/pyenv/bin:/Users/christiankjaerlaustsen/.nix-profile/bin:/Users/christiankjaerlaustsen/.nix-profile/sbin:/Users/christiankjaerlaustsen/.nix-profile/lib/kde4/libexec:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/nix/var/nix/profiles/default/lib/kde4/libexec:/Users/christiankjaerlaustsen/Bitbucket/blackbird/cli/bin:/Users/christiankjaerlaustsen/.local/go/bin:/Users/christiankjaerlaustsen/.local/bin:/usr/local/sbin:/Users/christiankjaerlaustsen/.cargo/bin:/Users/christiankjaerlaustsen/.rvm/bin
+ [nodenv:78] NODENV_HOOK_PATH=:/Users/christiankjaerlaustsen/.nodenv/nodenv.d
+ [nodenv:79] '[' /usr/local/Cellar/nodenv/1.1.2 '!=' /Users/christiankjaerlaustsen/.nodenv ']'
+ [nodenv:81] NODENV_HOOK_PATH=:/Users/christiankjaerlaustsen/.nodenv/nodenv.d:/usr/local/Cellar/nodenv/1.1.2/nodenv.d
+ [nodenv:83] NODENV_HOOK_PATH=:/Users/christiankjaerlaustsen/.nodenv/nodenv.d:/usr/local/Cellar/nodenv/1.1.2/nodenv.d:/usr/local/etc/nodenv.d:/etc/nodenv.d:/usr/lib/nodenv/hooks
+ [nodenv:87] NODENV_HOOK_PATH=/Users/christiankjaerlaustsen/.nodenv/nodenv.d:/usr/local/Cellar/nodenv/1.1.2/nodenv.d:/usr/local/etc/nodenv.d:/etc/nodenv.d:/usr/lib/nodenv/hooks
+ [nodenv:88] export NODENV_HOOK_PATH
+ [nodenv:90] shopt -u nullglob
+ [nodenv:93] command=shell
+ [nodenv:94] case "$command" in
++ [nodenv:107] command -v nodenv-shell
++ [nodenv:107] true
+ [nodenv:107] command_path=
+ [nodenv:108] '[' -n '' ']'
+ [nodenv:108] abort 'no such command `shell'\'''
+ [nodenv:16] '[' 1 -eq 0 ']'
+ [nodenv:17] echo 'nodenv: no such command `shell'\'''
nodenv: no such command `shell'
+ [nodenv:20] exit 1
```

I suspect this is probably a setup thing, but can't quite see what is wrong yet.

**Comment by Tehnix** [comment] 2018-02-20 08:31
Aaaan nevermind, seemed that `eval "$(nodenv init -)"` had not been running correctly, but is now. For anyone hitting the same issue, make sure you actually run `eval "$(nodenv init -)"` in your .bashrc/.zshrc file.
