### ISSUE TITLE
Correct Mac OS X homebrew install instructions

### ISSUE THREAD

**Issue by simonsvd** [OiNutter/nodenv#28] opened 2015-11-04 13:47 UTC
These are the proper steps, at least on Homebrew for Mac OS X 10.9. The difference is line 3: 
```
$ brew update
$ brew tap jawshooah/nodenv
$ brew install nodenv
$ brew install --HEAD node-build
```

**Comment by jasonkarns** [comment] 2015-11-04 14:22
dupe of #26 (and closed with e571fb77a12fe9db06a5c52e836f47fcbf53f4d7)

**Closed by jasonkarns** 2015-11-04 14:22 UTC
